// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.cshep4.premierpredictor.request;

public interface EmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.EmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
