// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.cshep4.premierpredictor.request;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
