// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.cshep4.premierpredictor.request;

public interface PredictionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.PredictionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string matchId = 2;</code>
   */
  java.lang.String getMatchId();
  /**
   * <code>string matchId = 2;</code>
   */
  com.google.protobuf.ByteString
      getMatchIdBytes();
}
