// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cshep4/premier-predictor-microservices/src/predictionservice/internal/interfaces (interfaces: FixtureClientFactory)

// Package factorymocks is a generated GoMock package.
package factorymocks

import (
	gen "github.com/cshep4/premier-predictor-microservices/proto-gen/model/gen"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFixtureClientFactory is a mock of FixtureClientFactory interface
type MockFixtureClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFixtureClientFactoryMockRecorder
}

// MockFixtureClientFactoryMockRecorder is the mock recorder for MockFixtureClientFactory
type MockFixtureClientFactoryMockRecorder struct {
	mock *MockFixtureClientFactory
}

// NewMockFixtureClientFactory creates a new mock instance
func NewMockFixtureClientFactory(ctrl *gomock.Controller) *MockFixtureClientFactory {
	mock := &MockFixtureClientFactory{ctrl: ctrl}
	mock.recorder = &MockFixtureClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFixtureClientFactory) EXPECT() *MockFixtureClientFactoryMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method
func (m *MockFixtureClientFactory) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection
func (mr *MockFixtureClientFactoryMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockFixtureClientFactory)(nil).CloseConnection))
}

// NewFixtureClient mocks base method
func (m *MockFixtureClientFactory) NewFixtureClient() (gen.FixtureServiceClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFixtureClient")
	ret0, _ := ret[0].(gen.FixtureServiceClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFixtureClient indicates an expected call of NewFixtureClient
func (mr *MockFixtureClientFactoryMockRecorder) NewFixtureClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFixtureClient", reflect.TypeOf((*MockFixtureClientFactory)(nil).NewFixtureClient))
}
