// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.cshep4.premierpredictor.auth;

public interface ValidateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ValidateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
