// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

public interface GroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.GroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string userIds = 1;</code>
   */
  java.util.List<java.lang.String>
      getUserIdsList();
  /**
   * <code>repeated string userIds = 1;</code>
   */
  int getUserIdsCount();
  /**
   * <code>repeated string userIds = 1;</code>
   */
  java.lang.String getUserIds(int index);
  /**
   * <code>repeated string userIds = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdsBytes(int index);

  /**
   * <code>.model.Notification notification = 2;</code>
   */
  boolean hasNotification();
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  com.cshep4.premierpredictor.notification.Notification getNotification();
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  com.cshep4.premierpredictor.notification.NotificationOrBuilder getNotificationOrBuilder();
}
