// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

public final class NotificationOuterClass {
  private NotificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_SaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_SaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_SingleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_SingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_GroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Notification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022notification.proto\022\005model\032\033google/prot" +
      "obuf/empty.proto\"8\n\013SaveRequest\022\016\n\006userI" +
      "d\030\001 \001(\t\022\031\n\021notificationToken\030\002 \001(\t\"J\n\rSi" +
      "ngleRequest\022\016\n\006userId\030\001 \001(\t\022)\n\014notificat" +
      "ion\030\002 \001(\0132\023.model.Notification\"J\n\014GroupR" +
      "equest\022\017\n\007userIds\030\001 \003(\t\022)\n\014notification\030" +
      "\002 \001(\0132\023.model.Notification\".\n\014Notificati" +
      "on\022\r\n\005title\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2\201\002\n\023N" +
      "otificationService\0228\n\010SaveUser\022\022.model.S" +
      "aveRequest\032\026.google.protobuf.Empty\"\000\0226\n\004",
      "Send\022\024.model.SingleRequest\032\026.google.prot" +
      "obuf.Empty\"\000\022<\n\013SendToGroup\022\023.model.Grou" +
      "pRequest\032\026.google.protobuf.Empty\"\000\022:\n\tSe" +
      "ndToAll\022\023.model.Notification\032\026.google.pr" +
      "otobuf.Empty\"\000B,\n(com.cshep4.premierpred" +
      "ictor.notificationP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_model_SaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_SaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_SaveRequest_descriptor,
        new java.lang.String[] { "UserId", "NotificationToken", });
    internal_static_model_SingleRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_SingleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_SingleRequest_descriptor,
        new java.lang.String[] { "UserId", "Notification", });
    internal_static_model_GroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_GroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_GroupRequest_descriptor,
        new java.lang.String[] { "UserIds", "Notification", });
    internal_static_model_Notification_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_model_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Notification_descriptor,
        new java.lang.String[] { "Title", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
