// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

public interface SaveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.SaveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string notificationToken = 2;</code>
   */
  java.lang.String getNotificationToken();
  /**
   * <code>string notificationToken = 2;</code>
   */
  com.google.protobuf.ByteString
      getNotificationTokenBytes();
}
