// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

/**
 * Protobuf type {@code model.SingleRequest}
 */
public  final class SingleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.SingleRequest)
    SingleRequestOrBuilder {
  // Use SingleRequest.newBuilder() to construct.
  private SingleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SingleRequest() {
    userId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SingleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            com.cshep4.premierpredictor.notification.Notification.Builder subBuilder = null;
            if (notification_ != null) {
              subBuilder = notification_.toBuilder();
            }
            notification_ = input.readMessage(com.cshep4.premierpredictor.notification.Notification.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(notification_);
              notification_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cshep4.premierpredictor.notification.NotificationOuterClass.internal_static_model_SingleRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cshep4.premierpredictor.notification.NotificationOuterClass.internal_static_model_SingleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cshep4.premierpredictor.notification.SingleRequest.class, com.cshep4.premierpredictor.notification.SingleRequest.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATION_FIELD_NUMBER = 2;
  private com.cshep4.premierpredictor.notification.Notification notification_;
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  public boolean hasNotification() {
    return notification_ != null;
  }
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  public com.cshep4.premierpredictor.notification.Notification getNotification() {
    return notification_ == null ? com.cshep4.premierpredictor.notification.Notification.getDefaultInstance() : notification_;
  }
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  public com.cshep4.premierpredictor.notification.NotificationOrBuilder getNotificationOrBuilder() {
    return getNotification();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (notification_ != null) {
      output.writeMessage(2, getNotification());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (notification_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNotification());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cshep4.premierpredictor.notification.SingleRequest)) {
      return super.equals(obj);
    }
    com.cshep4.premierpredictor.notification.SingleRequest other = (com.cshep4.premierpredictor.notification.SingleRequest) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && (hasNotification() == other.hasNotification());
    if (hasNotification()) {
      result = result && getNotification()
          .equals(other.getNotification());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (hasNotification()) {
      hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getNotification().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cshep4.premierpredictor.notification.SingleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cshep4.premierpredictor.notification.SingleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.SingleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.SingleRequest)
      com.cshep4.premierpredictor.notification.SingleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cshep4.premierpredictor.notification.NotificationOuterClass.internal_static_model_SingleRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cshep4.premierpredictor.notification.NotificationOuterClass.internal_static_model_SingleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cshep4.premierpredictor.notification.SingleRequest.class, com.cshep4.premierpredictor.notification.SingleRequest.Builder.class);
    }

    // Construct using com.cshep4.premierpredictor.notification.SingleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = "";

      if (notificationBuilder_ == null) {
        notification_ = null;
      } else {
        notification_ = null;
        notificationBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cshep4.premierpredictor.notification.NotificationOuterClass.internal_static_model_SingleRequest_descriptor;
    }

    public com.cshep4.premierpredictor.notification.SingleRequest getDefaultInstanceForType() {
      return com.cshep4.premierpredictor.notification.SingleRequest.getDefaultInstance();
    }

    public com.cshep4.premierpredictor.notification.SingleRequest build() {
      com.cshep4.premierpredictor.notification.SingleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cshep4.premierpredictor.notification.SingleRequest buildPartial() {
      com.cshep4.premierpredictor.notification.SingleRequest result = new com.cshep4.premierpredictor.notification.SingleRequest(this);
      result.userId_ = userId_;
      if (notificationBuilder_ == null) {
        result.notification_ = notification_;
      } else {
        result.notification_ = notificationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cshep4.premierpredictor.notification.SingleRequest) {
        return mergeFrom((com.cshep4.premierpredictor.notification.SingleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cshep4.premierpredictor.notification.SingleRequest other) {
      if (other == com.cshep4.premierpredictor.notification.SingleRequest.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasNotification()) {
        mergeNotification(other.getNotification());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cshep4.premierpredictor.notification.SingleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cshep4.premierpredictor.notification.SingleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private com.cshep4.premierpredictor.notification.Notification notification_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cshep4.premierpredictor.notification.Notification, com.cshep4.premierpredictor.notification.Notification.Builder, com.cshep4.premierpredictor.notification.NotificationOrBuilder> notificationBuilder_;
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public boolean hasNotification() {
      return notificationBuilder_ != null || notification_ != null;
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public com.cshep4.premierpredictor.notification.Notification getNotification() {
      if (notificationBuilder_ == null) {
        return notification_ == null ? com.cshep4.premierpredictor.notification.Notification.getDefaultInstance() : notification_;
      } else {
        return notificationBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public Builder setNotification(com.cshep4.premierpredictor.notification.Notification value) {
      if (notificationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        notification_ = value;
        onChanged();
      } else {
        notificationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public Builder setNotification(
        com.cshep4.premierpredictor.notification.Notification.Builder builderForValue) {
      if (notificationBuilder_ == null) {
        notification_ = builderForValue.build();
        onChanged();
      } else {
        notificationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public Builder mergeNotification(com.cshep4.premierpredictor.notification.Notification value) {
      if (notificationBuilder_ == null) {
        if (notification_ != null) {
          notification_ =
            com.cshep4.premierpredictor.notification.Notification.newBuilder(notification_).mergeFrom(value).buildPartial();
        } else {
          notification_ = value;
        }
        onChanged();
      } else {
        notificationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public Builder clearNotification() {
      if (notificationBuilder_ == null) {
        notification_ = null;
        onChanged();
      } else {
        notification_ = null;
        notificationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public com.cshep4.premierpredictor.notification.Notification.Builder getNotificationBuilder() {
      
      onChanged();
      return getNotificationFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    public com.cshep4.premierpredictor.notification.NotificationOrBuilder getNotificationOrBuilder() {
      if (notificationBuilder_ != null) {
        return notificationBuilder_.getMessageOrBuilder();
      } else {
        return notification_ == null ?
            com.cshep4.premierpredictor.notification.Notification.getDefaultInstance() : notification_;
      }
    }
    /**
     * <code>.model.Notification notification = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cshep4.premierpredictor.notification.Notification, com.cshep4.premierpredictor.notification.Notification.Builder, com.cshep4.premierpredictor.notification.NotificationOrBuilder> 
        getNotificationFieldBuilder() {
      if (notificationBuilder_ == null) {
        notificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cshep4.premierpredictor.notification.Notification, com.cshep4.premierpredictor.notification.Notification.Builder, com.cshep4.premierpredictor.notification.NotificationOrBuilder>(
                getNotification(),
                getParentForChildren(),
                isClean());
        notification_ = null;
      }
      return notificationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:model.SingleRequest)
  }

  // @@protoc_insertion_point(class_scope:model.SingleRequest)
  private static final com.cshep4.premierpredictor.notification.SingleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cshep4.premierpredictor.notification.SingleRequest();
  }

  public static com.cshep4.premierpredictor.notification.SingleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SingleRequest>
      PARSER = new com.google.protobuf.AbstractParser<SingleRequest>() {
    public SingleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SingleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SingleRequest> getParserForType() {
    return PARSER;
  }

  public com.cshep4.premierpredictor.notification.SingleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

