// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

public interface SingleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.SingleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.model.Notification notification = 2;</code>
   */
  boolean hasNotification();
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  com.cshep4.premierpredictor.notification.Notification getNotification();
  /**
   * <code>.model.Notification notification = 2;</code>
   */
  com.cshep4.premierpredictor.notification.NotificationOrBuilder getNotificationOrBuilder();
}
