// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.cshep4.premierpredictor.notification;

public interface UpdateReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.UpdateReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string notificationId = 2;</code>
   */
  java.lang.String getNotificationId();
  /**
   * <code>string notificationId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();
}
